@startuml
'https://plantuml.com/class-diagram

interface UserDetailsService
interface UserDetailsManager
interface UserDetails
class InMemoryUserDetailsManager
class JdbcUserDetailsManager

class User
class MutableUserDetails

UserDetailsService <|-- UserDetailsManager
UserDetailsManager <|.. InMemoryUserDetailsManager
UserDetailsManager <|.. JdbcUserDetailsManager
UserDetails <|.. User
UserDetails <|-- MutableUserDetails


@enduml